-- =====================================================================
-- Lo mínimo de Supabase y de pj.fire para probar las migraciones del
-- Plan en un PostgreSQL local (no se usa en producción).
-- Roles anon/authenticated/authenticator, auth.users, auth.uid() como en
-- Supabase (lee el sub del JWT que pone PostgREST) y las tablas de
-- pj.fire que el Plan necesita, con sus políticas reales.
-- =====================================================================
do $$ begin
  if not exists (select 1 from pg_roles where rolname = 'anon') then create role anon nologin noinherit; end if;
  if not exists (select 1 from pg_roles where rolname = 'authenticated') then create role authenticated nologin noinherit; end if;
  if not exists (select 1 from pg_roles where rolname = 'service_role') then create role service_role nologin noinherit bypassrls; end if;
  if not exists (select 1 from pg_roles where rolname = 'authenticator') then create role authenticator login noinherit; end if;
end $$;
grant anon, authenticated, service_role to authenticator;

create schema if not exists auth;
create schema if not exists extensions;
create extension if not exists pgcrypto with schema extensions;
create table if not exists auth.users (
  id uuid primary key,
  email text,
  created_at timestamptz not null default now()
);
create or replace function auth.uid() returns uuid language sql stable as $$
  select coalesce(
    nullif(current_setting('request.jwt.claim.sub', true), ''),
    (nullif(current_setting('request.jwt.claims', true), '')::jsonb ->> 'sub')
  )::uuid
$$;
grant usage on schema auth to anon, authenticated, service_role;
grant usage on schema public to anon, authenticated, service_role;
grant usage on schema extensions to anon, authenticated, service_role;
-- Como en Supabase: anon y authenticated tienen todos los permisos sobre
-- las tablas de public; lo que de verdad protege es la RLS.
alter default privileges in schema public grant all on tables to anon, authenticated, service_role;
alter default privileges in schema public grant all on sequences to anon, authenticated, service_role;
alter default privileges in schema public grant execute on functions to anon, authenticated, service_role;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  is_admin boolean not null default false,
  device_limit int not null default 2,
  approved boolean not null default false,
  blocked boolean not null default false,
  feature_flags jsonb not null default '{}'::jsonb,
  es_profesor boolean not null default false
);
alter table public.profiles enable row level security;
drop policy if exists "profile select own" on public.profiles;
create policy "profile select own" on public.profiles for select using (auth.uid() = id);

create table if not exists public.app_settings (
  key text primary key,
  value jsonb not null,
  updated_at timestamptz not null default now()
);
alter table public.app_settings enable row level security;

create table if not exists public.topics (
  id text primary key,
  category text not null default '',
  name text not null,
  description text,
  enabled boolean not null default true,
  sort_order int not null default 0
);
alter table public.topics enable row level security;
drop policy if exists "public read topics" on public.topics;
create policy "public read topics" on public.topics for select using (true);

create table if not exists public.questions (
  id bigint generated by default as identity primary key,
  difficulty text not null default 'media',
  question text not null,
  options jsonb not null,
  correct_index int not null,
  explain text not null default '',
  nodo_id uuid,
  topic_id text not null references public.topics(id) on delete cascade,
  ai_explain jsonb,
  own_note jsonb,
  updated_at timestamptz not null default now()
);
alter table public.questions enable row level security;
drop policy if exists "public read questions" on public.questions;
create policy "public read questions" on public.questions for select using (true);

create table if not exists public.test_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  mode text not null,
  score numeric,
  total int not null,
  ok int not null,
  bad int not null,
  pending int not null,
  time_seconds int,
  created_at timestamptz not null default now(),
  pending_question_ids jsonb not null default '[]'::jsonb
);
alter table public.test_sessions enable row level security;
drop policy if exists "sessions select own" on public.test_sessions;
create policy "sessions select own" on public.test_sessions for select using (auth.uid() = user_id);
drop policy if exists "sessions insert own" on public.test_sessions;
create policy "sessions insert own" on public.test_sessions for insert with check (auth.uid() = user_id);
drop policy if exists "sessions delete own" on public.test_sessions;
create policy "sessions delete own" on public.test_sessions for delete using (auth.uid() = user_id);

create table if not exists public.session_answers (
  id bigint generated by default as identity primary key,
  session_id uuid not null references public.test_sessions(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  question_id bigint not null references public.questions(id) on delete cascade,
  selected_index int,
  is_correct boolean not null default false,
  answer_order int not null default 0
);
alter table public.session_answers enable row level security;
drop policy if exists "answers select own" on public.session_answers;
create policy "answers select own" on public.session_answers for select using (auth.uid() = user_id);
drop policy if exists "answers insert own" on public.session_answers;
create policy "answers insert own" on public.session_answers for insert with check (auth.uid() = user_id);
drop policy if exists "answers delete own" on public.session_answers;
create policy "answers delete own" on public.session_answers for delete using (auth.uid() = user_id);
