-- =====================================================================
-- Pruebas E2E del Plan: lo que el arranque de pj.fire consulta y no está
-- en tests/plan/db/supabase_base.sql (con la forma que espera el código),
-- y los datos de prueba. Solo para la base de datos local de las pruebas.
-- =====================================================================
create table if not exists public.nodos_temario (
  id uuid primary key default gen_random_uuid(),
  topic_id text not null references public.topics(id) on delete cascade,
  padre_id uuid, tipo text not null default 'titulo', numero text, nombre text, orden int not null default 0,
  created_at timestamptz not null default now()
);
alter table public.nodos_temario enable row level security;
drop policy if exists "leer nodos" on public.nodos_temario;
create policy "leer nodos" on public.nodos_temario for select using (true);

create table if not exists public.questions_deleted (id bigint primary key, deleted_at timestamptz not null default now());
alter table public.questions_deleted enable row level security;
drop policy if exists "leer borradas" on public.questions_deleted;
create policy "leer borradas" on public.questions_deleted for select using (true);

create table if not exists public.dismissed_fails (
  user_id uuid not null references auth.users(id) on delete cascade,
  question_id bigint not null references public.questions(id) on delete cascade,
  dismissed_at timestamptz not null default now(),
  primary key (user_id, question_id)
);
alter table public.dismissed_fails enable row level security;
drop policy if exists "propios" on public.dismissed_fails;
create policy "propios" on public.dismissed_fails for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create table if not exists public.login_attempts (
  id bigint generated by default as identity primary key, email text, success boolean, reason text, user_id uuid,
  device_id text, user_agent text, created_at timestamptz not null default now()
);
alter table public.login_attempts enable row level security;
drop policy if exists "insertar" on public.login_attempts;
create policy "insertar" on public.login_attempts for insert with check (true);

create table if not exists public.client_errors (
  id bigint generated by default as identity primary key, user_id uuid, kind text, message text, stack text, url text,
  user_agent text, created_at timestamptz not null default now()
);
alter table public.client_errors enable row level security;
drop policy if exists "insertar" on public.client_errors;
create policy "insertar" on public.client_errors for insert with check (true);

create table if not exists public.nq_sets (id uuid primary key default gen_random_uuid(), title text, orden int default 0, created_at timestamptz default now());
create table if not exists public.nq_cards (id uuid primary key default gen_random_uuid(), set_id uuid, term text, definition text, trampas jsonb, orden int default 0, created_at timestamptz default now());
create table if not exists public.nq_user_progress (user_id uuid primary key, data jsonb not null default '{}', updated_at timestamptz not null default now());
alter table public.nq_sets enable row level security;
alter table public.nq_cards enable row level security;
alter table public.nq_user_progress enable row level security;
drop policy if exists "leer" on public.nq_sets; create policy "leer" on public.nq_sets for select using (true);
drop policy if exists "leer" on public.nq_cards; create policy "leer" on public.nq_cards for select using (true);
drop policy if exists "propio" on public.nq_user_progress;
create policy "propio" on public.nq_user_progress for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create or replace function public.register_device_and_check_limit(p_device_id text, p_user_agent text)
returns jsonb language sql as $$ select jsonb_build_object('allowed', true) $$;
create or replace function public.heartbeat_activity(p_device_id text)
returns void language sql as $$ select null::void $$;
create or replace function public.get_my_question_data(p_question_ids bigint[])
returns table(question_id bigint, own_note jsonb, ai_explain jsonb) language sql as $$ select null::bigint, null::jsonb, null::jsonb where false $$;
create or replace function public.callejero_avisos()
returns jsonb language sql as $$ select jsonb_build_object('tareas_nuevas', 0, 'mensajes', 0) $$;

grant select, insert, update, delete on all tables in schema public to anon, authenticated;
grant execute on all functions in schema public to authenticated;
-- La migración del Plan quita estos permisos a anon: se vuelven a quitar
-- por si el grant de arriba los hubiera devuelto.
revoke all on public.plan_ajustes, public.plan_temas, public.plan_tests, public.plan_tareas,
  public.plan_resultados, public.plan_eventos, public.plan_preguntas from anon;

-- ---------- datos de prueba ----------
insert into auth.users (id, email) values
  ('00000000-0000-4000-8000-0000000000a1', 'admin@prueba.es'),
  ('00000000-0000-4000-8000-0000000000a2', 'alumno@prueba.es'),
  ('00000000-0000-4000-8000-0000000000a3', 'alumna@prueba.es')
on conflict do nothing;
insert into public.profiles (id, is_admin, approved, feature_flags) values
  ('00000000-0000-4000-8000-0000000000a1', true, true, '{}'),
  ('00000000-0000-4000-8000-0000000000a2', false, true, '{"callejero":false,"normativas":false}'),
  ('00000000-0000-4000-8000-0000000000a3', false, true, '{"plan":true,"callejero":false,"normativas":false}')
on conflict (id) do nothing;
insert into public.app_settings (key, value) values ('default_feature_flags', '{"callejero":false}') on conflict do nothing;
insert into public.topics (id, name, sort_order) values ('CE', 'Constitución Española', 1), ('PRL', 'Prevención de Riesgos Laborales', 2)
on conflict do nothing;
insert into public.questions (question, options, correct_index, explain, topic_id)
select 'Pregunta ' || t.id || ' número ' || g || E'\nSegunda línea del enunciado.',
       jsonb_build_array('Opción A de ' || g, 'Opción B de ' || g, 'Opción C de ' || g, 'Opción D de ' || g),
       (g % 4), 'Explicación de la pregunta ' || g || ' de ' || t.id, t.id
from public.topics t, generate_series(1, 40) g
where not exists (select 1 from public.questions);
